name: Run with Telemetry
description: >
  Execute a command on the runner and export the associated OpenTelemetry
  trace.
author: Kristof Kowalski
inputs:
  github-token:
    required: false
    default: ${{ github.token }}
    description: A token that can be used with the GitHub API.
  headers:
    required: false
    description: >
      Headers to attach to outgoing gRPC requests. Set via comma
      separated values; header1=value1,header2=value2.
  is-root:
    required: false
    description: >
      This is the root span, denoting the beginning of an operation.
  otel-exporter-otlp-endpoint:
    required: true
    description: >
      A base endpoint URL for any signal type, with an optionally-specified
      port number.
  otel-resource-attributes:
    required: false
    description: >
      Key-value pairs to be used as resource attributes. Set via comma
      seperated values; key1=value1,key2=value2
  otel-service-name:
    required: true
    description: >
      Logical name of the service. Sets the value of the service.name resource
      attribute.
  run:
    required: true
    description: >
      The command to run.
  shell:
    required: false
    description: >
      You can override the default shell settings in the runner's operating
      system using the shell keyword. Supported options are bash, pwsh,
      python, sh, cmd, pwsh and powershell. The default is bash.
  step-name:
    required: true
    description: >
      The name of the step.

runs:
  using: node16
  main: index.js

branding:
  icon: person-running
  color: gray-dark
